# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '_dialog_random_points.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog_random_points(object):
    def setupUi(self, Dialog_random_points):
        Dialog_random_points.setObjectName(_fromUtf8("Dialog_random_points"))
        Dialog_random_points.resize(616, 319)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog_random_points.sizePolicy().hasHeightForWidth())
        Dialog_random_points.setSizePolicy(sizePolicy)
        Dialog_random_points.setMinimumSize(QtCore.QSize(350, 300))
        Dialog_random_points.setMaximumSize(QtCore.QSize(16777215, 319))
        Dialog_random_points.setSizeGripEnabled(True)
        Dialog_random_points.setModal(True)
        self.gridLayout_2 = QtGui.QGridLayout(Dialog_random_points)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.horizontalSlider_random_points_points_num = QtGui.QSlider(Dialog_random_points)
        self.horizontalSlider_random_points_points_num.setMinimum(1)
        self.horizontalSlider_random_points_points_num.setMaximum(1000)
        self.horizontalSlider_random_points_points_num.setProperty("value", 100)
        self.horizontalSlider_random_points_points_num.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_random_points_points_num.setObjectName(_fromUtf8("horizontalSlider_random_points_points_num"))
        self.gridLayout_2.addWidget(self.horizontalSlider_random_points_points_num, 0, 1, 1, 1)
        self.label = QtGui.QLabel(Dialog_random_points)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.spinBox_random_points_points_num = QtGui.QSpinBox(Dialog_random_points)
        self.spinBox_random_points_points_num.setMinimum(1)
        self.spinBox_random_points_points_num.setMaximum(1000)
        self.spinBox_random_points_points_num.setProperty("value", 100)
        self.spinBox_random_points_points_num.setObjectName(_fromUtf8("spinBox_random_points_points_num"))
        self.gridLayout_2.addWidget(self.spinBox_random_points_points_num, 0, 2, 1, 1)
        self.groupBox = QtGui.QGroupBox(Dialog_random_points)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.horizontalSlider_random_points_min_y = QtGui.QSlider(self.groupBox)
        self.horizontalSlider_random_points_min_y.setMinimum(-500)
        self.horizontalSlider_random_points_min_y.setMaximum(500)
        self.horizontalSlider_random_points_min_y.setSliderPosition(-10)
        self.horizontalSlider_random_points_min_y.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_random_points_min_y.setObjectName(_fromUtf8("horizontalSlider_random_points_min_y"))
        self.gridLayout.addWidget(self.horizontalSlider_random_points_min_y, 2, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.horizontalSlider_random_points_max_y = QtGui.QSlider(self.groupBox)
        self.horizontalSlider_random_points_max_y.setMinimum(-500)
        self.horizontalSlider_random_points_max_y.setMaximum(500)
        self.horizontalSlider_random_points_max_y.setSliderPosition(10)
        self.horizontalSlider_random_points_max_y.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_random_points_max_y.setObjectName(_fromUtf8("horizontalSlider_random_points_max_y"))
        self.gridLayout.addWidget(self.horizontalSlider_random_points_max_y, 3, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.groupBox)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 4, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.horizontalSlider_random_points_max_x = QtGui.QSlider(self.groupBox)
        self.horizontalSlider_random_points_max_x.setMinimum(-500)
        self.horizontalSlider_random_points_max_x.setMaximum(500)
        self.horizontalSlider_random_points_max_x.setSliderPosition(10)
        self.horizontalSlider_random_points_max_x.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_random_points_max_x.setObjectName(_fromUtf8("horizontalSlider_random_points_max_x"))
        self.gridLayout.addWidget(self.horizontalSlider_random_points_max_x, 1, 1, 1, 1)
        self.label_7 = QtGui.QLabel(self.groupBox)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 5, 0, 1, 1)
        self.horizontalSlider_random_points_min_x = QtGui.QSlider(self.groupBox)
        self.horizontalSlider_random_points_min_x.setMinimum(-500)
        self.horizontalSlider_random_points_min_x.setMaximum(500)
        self.horizontalSlider_random_points_min_x.setSliderPosition(-10)
        self.horizontalSlider_random_points_min_x.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_random_points_min_x.setObjectName(_fromUtf8("horizontalSlider_random_points_min_x"))
        self.gridLayout.addWidget(self.horizontalSlider_random_points_min_x, 0, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.label_5 = QtGui.QLabel(self.groupBox)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 2, 0, 1, 1)
        self.horizontalSlider_random_points_min_z = QtGui.QSlider(self.groupBox)
        self.horizontalSlider_random_points_min_z.setMinimum(-500)
        self.horizontalSlider_random_points_min_z.setMaximum(500)
        self.horizontalSlider_random_points_min_z.setSliderPosition(-10)
        self.horizontalSlider_random_points_min_z.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_random_points_min_z.setObjectName(_fromUtf8("horizontalSlider_random_points_min_z"))
        self.gridLayout.addWidget(self.horizontalSlider_random_points_min_z, 4, 1, 1, 1)
        self.horizontalSlider_random_points_max_z = QtGui.QSlider(self.groupBox)
        self.horizontalSlider_random_points_max_z.setMinimum(-500)
        self.horizontalSlider_random_points_max_z.setMaximum(500)
        self.horizontalSlider_random_points_max_z.setSliderPosition(10)
        self.horizontalSlider_random_points_max_z.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_random_points_max_z.setObjectName(_fromUtf8("horizontalSlider_random_points_max_z"))
        self.gridLayout.addWidget(self.horizontalSlider_random_points_max_z, 5, 1, 1, 1)
        self.spinBox_random_points_min_x = QtGui.QSpinBox(self.groupBox)
        self.spinBox_random_points_min_x.setMinimum(-505)
        self.spinBox_random_points_min_x.setMaximum(500)
        self.spinBox_random_points_min_x.setProperty("value", -10)
        self.spinBox_random_points_min_x.setObjectName(_fromUtf8("spinBox_random_points_min_x"))
        self.gridLayout.addWidget(self.spinBox_random_points_min_x, 0, 2, 1, 1)
        self.spinBox_random_points_max_x = QtGui.QSpinBox(self.groupBox)
        self.spinBox_random_points_max_x.setMinimum(-500)
        self.spinBox_random_points_max_x.setMaximum(500)
        self.spinBox_random_points_max_x.setProperty("value", 10)
        self.spinBox_random_points_max_x.setObjectName(_fromUtf8("spinBox_random_points_max_x"))
        self.gridLayout.addWidget(self.spinBox_random_points_max_x, 1, 2, 1, 1)
        self.spinBox_random_points_min_y = QtGui.QSpinBox(self.groupBox)
        self.spinBox_random_points_min_y.setMinimum(-500)
        self.spinBox_random_points_min_y.setMaximum(500)
        self.spinBox_random_points_min_y.setProperty("value", -10)
        self.spinBox_random_points_min_y.setObjectName(_fromUtf8("spinBox_random_points_min_y"))
        self.gridLayout.addWidget(self.spinBox_random_points_min_y, 2, 2, 1, 1)
        self.spinBox_random_points_max_y = QtGui.QSpinBox(self.groupBox)
        self.spinBox_random_points_max_y.setMinimum(-500)
        self.spinBox_random_points_max_y.setMaximum(500)
        self.spinBox_random_points_max_y.setProperty("value", 10)
        self.spinBox_random_points_max_y.setObjectName(_fromUtf8("spinBox_random_points_max_y"))
        self.gridLayout.addWidget(self.spinBox_random_points_max_y, 3, 2, 1, 1)
        self.spinBox_random_points_min_z = QtGui.QSpinBox(self.groupBox)
        self.spinBox_random_points_min_z.setMinimum(-500)
        self.spinBox_random_points_min_z.setMaximum(500)
        self.spinBox_random_points_min_z.setProperty("value", -10)
        self.spinBox_random_points_min_z.setObjectName(_fromUtf8("spinBox_random_points_min_z"))
        self.gridLayout.addWidget(self.spinBox_random_points_min_z, 4, 2, 1, 1)
        self.spinBox_random_points_max_z = QtGui.QSpinBox(self.groupBox)
        self.spinBox_random_points_max_z.setMinimum(-500)
        self.spinBox_random_points_max_z.setMaximum(500)
        self.spinBox_random_points_max_z.setProperty("value", 10)
        self.spinBox_random_points_max_z.setObjectName(_fromUtf8("spinBox_random_points_max_z"))
        self.gridLayout.addWidget(self.spinBox_random_points_max_z, 5, 2, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox, 1, 0, 1, 3)
        self.buttonBox = QtGui.QDialogButtonBox(Dialog_random_points)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout_2.addWidget(self.buttonBox, 2, 0, 1, 3)
        self.buttonBox.raise_()
        self.label.raise_()
        self.groupBox.raise_()
        self.horizontalSlider_random_points_points_num.raise_()
        self.spinBox_random_points_points_num.raise_()

        self.retranslateUi(Dialog_random_points)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), Dialog_random_points.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), Dialog_random_points.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog_random_points)

    def retranslateUi(self, Dialog_random_points):
        Dialog_random_points.setWindowTitle(_translate("Dialog_random_points", "Generate Random Points", None))
        self.label.setText(_translate("Dialog_random_points", "Number of Points", None))
        self.groupBox.setTitle(_translate("Dialog_random_points", "Bounding Box", None))
        self.label_4.setText(_translate("Dialog_random_points", "Max-y", None))
        self.label_6.setText(_translate("Dialog_random_points", "Min-z", None))
        self.label_2.setText(_translate("Dialog_random_points", "Min-x", None))
        self.label_7.setText(_translate("Dialog_random_points", "Max-z", None))
        self.label_3.setText(_translate("Dialog_random_points", "Max-x", None))
        self.label_5.setText(_translate("Dialog_random_points", "Min-y", None))

