# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '_dialog_insert_shape.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog_insert_shape(object):
    def setupUi(self, Dialog_insert_shape):
        Dialog_insert_shape.setObjectName(_fromUtf8("Dialog_insert_shape"))
        Dialog_insert_shape.resize(377, 500)
        Dialog_insert_shape.setMinimumSize(QtCore.QSize(300, 500))
        self.gridLayout = QtGui.QGridLayout(Dialog_insert_shape)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.groupBox_scale = QtGui.QGroupBox(Dialog_insert_shape)
        self.groupBox_scale.setObjectName(_fromUtf8("groupBox_scale"))
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox_scale)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.horizontalSlider_scale_y = QtGui.QSlider(self.groupBox_scale)
        self.horizontalSlider_scale_y.setMinimum(-9900)
        self.horizontalSlider_scale_y.setMaximum(9900)
        self.horizontalSlider_scale_y.setSingleStep(10)
        self.horizontalSlider_scale_y.setProperty("value", 0)
        self.horizontalSlider_scale_y.setSliderPosition(0)
        self.horizontalSlider_scale_y.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_scale_y.setObjectName(_fromUtf8("horizontalSlider_scale_y"))
        self.gridLayout_4.addWidget(self.horizontalSlider_scale_y, 1, 1, 1, 1)
        self.doubleSpinBox_scale_y = QtGui.QDoubleSpinBox(self.groupBox_scale)
        self.doubleSpinBox_scale_y.setMinimum(0.01)
        self.doubleSpinBox_scale_y.setMaximum(100.0)
        self.doubleSpinBox_scale_y.setSingleStep(0.1)
        self.doubleSpinBox_scale_y.setProperty("value", 1.0)
        self.doubleSpinBox_scale_y.setObjectName(_fromUtf8("doubleSpinBox_scale_y"))
        self.gridLayout_4.addWidget(self.doubleSpinBox_scale_y, 1, 2, 1, 1)
        self.doubleSpinBox_scale_x = QtGui.QDoubleSpinBox(self.groupBox_scale)
        self.doubleSpinBox_scale_x.setMinimumSize(QtCore.QSize(72, 0))
        self.doubleSpinBox_scale_x.setMinimum(0.01)
        self.doubleSpinBox_scale_x.setMaximum(100.0)
        self.doubleSpinBox_scale_x.setSingleStep(0.1)
        self.doubleSpinBox_scale_x.setProperty("value", 1.0)
        self.doubleSpinBox_scale_x.setObjectName(_fromUtf8("doubleSpinBox_scale_x"))
        self.gridLayout_4.addWidget(self.doubleSpinBox_scale_x, 0, 2, 1, 1)
        self.label_7 = QtGui.QLabel(self.groupBox_scale)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_4.addWidget(self.label_7, 1, 0, 1, 1)
        self.label_8 = QtGui.QLabel(self.groupBox_scale)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_4.addWidget(self.label_8, 0, 0, 1, 1)
        self.horizontalSlider_scale_x = QtGui.QSlider(self.groupBox_scale)
        self.horizontalSlider_scale_x.setMinimum(-9900)
        self.horizontalSlider_scale_x.setMaximum(9900)
        self.horizontalSlider_scale_x.setSingleStep(10)
        self.horizontalSlider_scale_x.setProperty("value", 1)
        self.horizontalSlider_scale_x.setSliderPosition(1)
        self.horizontalSlider_scale_x.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_scale_x.setTickPosition(QtGui.QSlider.NoTicks)
        self.horizontalSlider_scale_x.setObjectName(_fromUtf8("horizontalSlider_scale_x"))
        self.gridLayout_4.addWidget(self.horizontalSlider_scale_x, 0, 1, 1, 1)
        self.label_9 = QtGui.QLabel(self.groupBox_scale)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_4.addWidget(self.label_9, 2, 0, 1, 1)
        self.horizontalSlider_scale_z = QtGui.QSlider(self.groupBox_scale)
        self.horizontalSlider_scale_z.setMinimum(-9900)
        self.horizontalSlider_scale_z.setMaximum(9900)
        self.horizontalSlider_scale_z.setSingleStep(10)
        self.horizontalSlider_scale_z.setProperty("value", 1)
        self.horizontalSlider_scale_z.setSliderPosition(1)
        self.horizontalSlider_scale_z.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_scale_z.setObjectName(_fromUtf8("horizontalSlider_scale_z"))
        self.gridLayout_4.addWidget(self.horizontalSlider_scale_z, 2, 1, 1, 1)
        self.doubleSpinBox_scale_z = QtGui.QDoubleSpinBox(self.groupBox_scale)
        self.doubleSpinBox_scale_z.setMinimum(0.01)
        self.doubleSpinBox_scale_z.setMaximum(100.0)
        self.doubleSpinBox_scale_z.setSingleStep(0.1)
        self.doubleSpinBox_scale_z.setProperty("value", 1.0)
        self.doubleSpinBox_scale_z.setObjectName(_fromUtf8("doubleSpinBox_scale_z"))
        self.gridLayout_4.addWidget(self.doubleSpinBox_scale_z, 2, 2, 1, 1)
        self.gridLayout.addWidget(self.groupBox_scale, 6, 1, 1, 1)
        self.buttonBox = QtGui.QDialogButtonBox(Dialog_insert_shape)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout.addWidget(self.buttonBox, 7, 1, 1, 1)
        self.groupBox_rotation = QtGui.QGroupBox(Dialog_insert_shape)
        self.groupBox_rotation.setObjectName(_fromUtf8("groupBox_rotation"))
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox_rotation)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_5 = QtGui.QLabel(self.groupBox_rotation)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_3.addWidget(self.label_5, 0, 2, 1, 1)
        self.horizontalSlider_rotation_x = QtGui.QSlider(self.groupBox_rotation)
        self.horizontalSlider_rotation_x.setMinimum(-18000)
        self.horizontalSlider_rotation_x.setMaximum(18000)
        self.horizontalSlider_rotation_x.setSingleStep(10)
        self.horizontalSlider_rotation_x.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_rotation_x.setObjectName(_fromUtf8("horizontalSlider_rotation_x"))
        self.gridLayout_3.addWidget(self.horizontalSlider_rotation_x, 0, 3, 1, 1)
        self.doubleSpinBox_rotation_x = QtGui.QDoubleSpinBox(self.groupBox_rotation)
        self.doubleSpinBox_rotation_x.setMinimum(-180.0)
        self.doubleSpinBox_rotation_x.setMaximum(180.0)
        self.doubleSpinBox_rotation_x.setSingleStep(0.1)
        self.doubleSpinBox_rotation_x.setObjectName(_fromUtf8("doubleSpinBox_rotation_x"))
        self.gridLayout_3.addWidget(self.doubleSpinBox_rotation_x, 0, 4, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBox_rotation)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_3.addWidget(self.label_4, 1, 2, 1, 1)
        self.horizontalSlider_rotation_y = QtGui.QSlider(self.groupBox_rotation)
        self.horizontalSlider_rotation_y.setMinimum(-18000)
        self.horizontalSlider_rotation_y.setMaximum(18000)
        self.horizontalSlider_rotation_y.setSingleStep(10)
        self.horizontalSlider_rotation_y.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_rotation_y.setObjectName(_fromUtf8("horizontalSlider_rotation_y"))
        self.gridLayout_3.addWidget(self.horizontalSlider_rotation_y, 1, 3, 1, 1)
        self.doubleSpinBox_rotation_y = QtGui.QDoubleSpinBox(self.groupBox_rotation)
        self.doubleSpinBox_rotation_y.setMinimum(-180.0)
        self.doubleSpinBox_rotation_y.setMaximum(180.0)
        self.doubleSpinBox_rotation_y.setSingleStep(0.1)
        self.doubleSpinBox_rotation_y.setObjectName(_fromUtf8("doubleSpinBox_rotation_y"))
        self.gridLayout_3.addWidget(self.doubleSpinBox_rotation_y, 1, 4, 1, 1)
        self.label_6 = QtGui.QLabel(self.groupBox_rotation)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_3.addWidget(self.label_6, 2, 2, 1, 1)
        self.horizontalSlider_rotation_z = QtGui.QSlider(self.groupBox_rotation)
        self.horizontalSlider_rotation_z.setMinimum(-18000)
        self.horizontalSlider_rotation_z.setMaximum(18000)
        self.horizontalSlider_rotation_z.setSingleStep(10)
        self.horizontalSlider_rotation_z.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_rotation_z.setObjectName(_fromUtf8("horizontalSlider_rotation_z"))
        self.gridLayout_3.addWidget(self.horizontalSlider_rotation_z, 2, 3, 1, 1)
        self.doubleSpinBox_rotation_z = QtGui.QDoubleSpinBox(self.groupBox_rotation)
        self.doubleSpinBox_rotation_z.setMinimum(-180.0)
        self.doubleSpinBox_rotation_z.setMaximum(180.0)
        self.doubleSpinBox_rotation_z.setSingleStep(0.1)
        self.doubleSpinBox_rotation_z.setObjectName(_fromUtf8("doubleSpinBox_rotation_z"))
        self.gridLayout_3.addWidget(self.doubleSpinBox_rotation_z, 2, 4, 1, 1)
        self.gridLayout.addWidget(self.groupBox_rotation, 5, 1, 1, 1)
        self.groupBox_position = QtGui.QGroupBox(Dialog_insert_shape)
        self.groupBox_position.setObjectName(_fromUtf8("groupBox_position"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_position)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.horizontalSlider_position_x = QtGui.QSlider(self.groupBox_position)
        self.horizontalSlider_position_x.setMinimum(-50000)
        self.horizontalSlider_position_x.setMaximum(50000)
        self.horizontalSlider_position_x.setSingleStep(10)
        self.horizontalSlider_position_x.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_position_x.setInvertedAppearance(False)
        self.horizontalSlider_position_x.setObjectName(_fromUtf8("horizontalSlider_position_x"))
        self.gridLayout_2.addWidget(self.horizontalSlider_position_x, 0, 3, 1, 1)
        self.label = QtGui.QLabel(self.groupBox_position)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_2.addWidget(self.label, 0, 2, 1, 1)
        self.label_2 = QtGui.QLabel(self.groupBox_position)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_2.addWidget(self.label_2, 1, 2, 1, 1)
        self.horizontalSlider_position_y = QtGui.QSlider(self.groupBox_position)
        self.horizontalSlider_position_y.setMinimum(-50000)
        self.horizontalSlider_position_y.setMaximum(50000)
        self.horizontalSlider_position_y.setSingleStep(10)
        self.horizontalSlider_position_y.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_position_y.setObjectName(_fromUtf8("horizontalSlider_position_y"))
        self.gridLayout_2.addWidget(self.horizontalSlider_position_y, 1, 3, 1, 1)
        self.horizontalSlider_position_z = QtGui.QSlider(self.groupBox_position)
        self.horizontalSlider_position_z.setMinimum(-50000)
        self.horizontalSlider_position_z.setMaximum(50000)
        self.horizontalSlider_position_z.setSingleStep(10)
        self.horizontalSlider_position_z.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_position_z.setObjectName(_fromUtf8("horizontalSlider_position_z"))
        self.gridLayout_2.addWidget(self.horizontalSlider_position_z, 2, 3, 1, 1)
        self.label_3 = QtGui.QLabel(self.groupBox_position)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_2.addWidget(self.label_3, 2, 2, 1, 1)
        self.doubleSpinBox_position_z = QtGui.QDoubleSpinBox(self.groupBox_position)
        self.doubleSpinBox_position_z.setMinimum(-500.0)
        self.doubleSpinBox_position_z.setMaximum(500.0)
        self.doubleSpinBox_position_z.setSingleStep(0.1)
        self.doubleSpinBox_position_z.setObjectName(_fromUtf8("doubleSpinBox_position_z"))
        self.gridLayout_2.addWidget(self.doubleSpinBox_position_z, 2, 4, 1, 1)
        self.doubleSpinBox_position_y = QtGui.QDoubleSpinBox(self.groupBox_position)
        self.doubleSpinBox_position_y.setMinimum(-500.0)
        self.doubleSpinBox_position_y.setMaximum(500.0)
        self.doubleSpinBox_position_y.setSingleStep(0.1)
        self.doubleSpinBox_position_y.setObjectName(_fromUtf8("doubleSpinBox_position_y"))
        self.gridLayout_2.addWidget(self.doubleSpinBox_position_y, 1, 4, 1, 1)
        self.doubleSpinBox_position_x = QtGui.QDoubleSpinBox(self.groupBox_position)
        self.doubleSpinBox_position_x.setMinimum(-500.0)
        self.doubleSpinBox_position_x.setMaximum(500.0)
        self.doubleSpinBox_position_x.setSingleStep(0.1)
        self.doubleSpinBox_position_x.setObjectName(_fromUtf8("doubleSpinBox_position_x"))
        self.gridLayout_2.addWidget(self.doubleSpinBox_position_x, 0, 4, 1, 1)
        self.gridLayout.addWidget(self.groupBox_position, 4, 1, 1, 1)

        self.retranslateUi(Dialog_insert_shape)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), Dialog_insert_shape.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), Dialog_insert_shape.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog_insert_shape)
        Dialog_insert_shape.setTabOrder(self.buttonBox, self.horizontalSlider_position_x)
        Dialog_insert_shape.setTabOrder(self.horizontalSlider_position_x, self.doubleSpinBox_position_x)
        Dialog_insert_shape.setTabOrder(self.doubleSpinBox_position_x, self.horizontalSlider_position_y)
        Dialog_insert_shape.setTabOrder(self.horizontalSlider_position_y, self.doubleSpinBox_position_y)
        Dialog_insert_shape.setTabOrder(self.doubleSpinBox_position_y, self.horizontalSlider_position_z)
        Dialog_insert_shape.setTabOrder(self.horizontalSlider_position_z, self.doubleSpinBox_position_z)
        Dialog_insert_shape.setTabOrder(self.doubleSpinBox_position_z, self.horizontalSlider_rotation_x)
        Dialog_insert_shape.setTabOrder(self.horizontalSlider_rotation_x, self.doubleSpinBox_rotation_x)
        Dialog_insert_shape.setTabOrder(self.doubleSpinBox_rotation_x, self.horizontalSlider_rotation_y)
        Dialog_insert_shape.setTabOrder(self.horizontalSlider_rotation_y, self.doubleSpinBox_rotation_y)
        Dialog_insert_shape.setTabOrder(self.doubleSpinBox_rotation_y, self.horizontalSlider_rotation_z)
        Dialog_insert_shape.setTabOrder(self.horizontalSlider_rotation_z, self.doubleSpinBox_rotation_z)
        Dialog_insert_shape.setTabOrder(self.doubleSpinBox_rotation_z, self.horizontalSlider_scale_x)
        Dialog_insert_shape.setTabOrder(self.horizontalSlider_scale_x, self.doubleSpinBox_scale_x)
        Dialog_insert_shape.setTabOrder(self.doubleSpinBox_scale_x, self.horizontalSlider_scale_y)
        Dialog_insert_shape.setTabOrder(self.horizontalSlider_scale_y, self.doubleSpinBox_scale_y)
        Dialog_insert_shape.setTabOrder(self.doubleSpinBox_scale_y, self.horizontalSlider_scale_z)
        Dialog_insert_shape.setTabOrder(self.horizontalSlider_scale_z, self.doubleSpinBox_scale_z)

    def retranslateUi(self, Dialog_insert_shape):
        Dialog_insert_shape.setWindowTitle(_translate("Dialog_insert_shape", "Insert Shape", None))
        self.groupBox_scale.setTitle(_translate("Dialog_insert_shape", "Scale", None))
        self.label_7.setText(_translate("Dialog_insert_shape", "Y", None))
        self.label_8.setText(_translate("Dialog_insert_shape", "X", None))
        self.label_9.setText(_translate("Dialog_insert_shape", "Z", None))
        self.groupBox_rotation.setTitle(_translate("Dialog_insert_shape", "Rotation", None))
        self.label_5.setText(_translate("Dialog_insert_shape", "X", None))
        self.label_4.setText(_translate("Dialog_insert_shape", "Y", None))
        self.label_6.setText(_translate("Dialog_insert_shape", "Z", None))
        self.groupBox_position.setTitle(_translate("Dialog_insert_shape", "Position", None))
        self.label.setText(_translate("Dialog_insert_shape", "X", None))
        self.label_2.setText(_translate("Dialog_insert_shape", "Y", None))
        self.label_3.setText(_translate("Dialog_insert_shape", "Z", None))

