# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window_new3.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(640, 480)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(640, 480))
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.centralwidget = QtGui.QWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.splitter = QtGui.QSplitter(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
        self.splitter.setSizePolicy(sizePolicy)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setChildrenCollapsible(False)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.canvas_tools_frame = QtGui.QFrame(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.canvas_tools_frame.sizePolicy().hasHeightForWidth())
        self.canvas_tools_frame.setSizePolicy(sizePolicy)
        self.canvas_tools_frame.setMinimumSize(QtCore.QSize(300, 300))
        self.canvas_tools_frame.setFrameShape(QtGui.QFrame.NoFrame)
        self.canvas_tools_frame.setFrameShadow(QtGui.QFrame.Plain)
        self.canvas_tools_frame.setObjectName(_fromUtf8("canvas_tools_frame"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.canvas_tools_frame)
        self.horizontalLayout.setMargin(12)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.canvas = Canvas3d(self.canvas_tools_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.canvas.sizePolicy().hasHeightForWidth())
        self.canvas.setSizePolicy(sizePolicy)
        self.canvas.setMinimumSize(QtCore.QSize(300, 300))
        self.canvas.setObjectName(_fromUtf8("canvas"))
        self.horizontalLayout.addWidget(self.canvas)
        self.line_4 = QtGui.QFrame(self.canvas_tools_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_4.sizePolicy().hasHeightForWidth())
        self.line_4.setSizePolicy(sizePolicy)
        self.line_4.setFrameShape(QtGui.QFrame.VLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.horizontalLayout.addWidget(self.line_4)
        self.tools_info_frame = QtGui.QSplitter(self.canvas_tools_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tools_info_frame.sizePolicy().hasHeightForWidth())
        self.tools_info_frame.setSizePolicy(sizePolicy)
        self.tools_info_frame.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tools_info_frame.setOrientation(QtCore.Qt.Vertical)
        self.tools_info_frame.setChildrenCollapsible(False)
        self.tools_info_frame.setObjectName(_fromUtf8("tools_info_frame"))
        self.tools_frame = QtGui.QFrame(self.tools_info_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tools_frame.sizePolicy().hasHeightForWidth())
        self.tools_frame.setSizePolicy(sizePolicy)
        self.tools_frame.setMinimumSize(QtCore.QSize(0, 0))
        self.tools_frame.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tools_frame.setFrameShape(QtGui.QFrame.NoFrame)
        self.tools_frame.setFrameShadow(QtGui.QFrame.Plain)
        self.tools_frame.setObjectName(_fromUtf8("tools_frame"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.tools_frame)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, -1)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label = QtGui.QLabel(self.tools_frame)
        self.label.setMinimumSize(QtCore.QSize(0, 0))
        self.label.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_2.addWidget(self.label)
        self.tools_tabs = QtGui.QTabWidget(self.tools_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tools_tabs.sizePolicy().hasHeightForWidth())
        self.tools_tabs.setSizePolicy(sizePolicy)
        self.tools_tabs.setMinimumSize(QtCore.QSize(0, 100))
        self.tools_tabs.setMaximumSize(QtCore.QSize(16777215, 16777209))
        self.tools_tabs.setUsesScrollButtons(False)
        self.tools_tabs.setObjectName(_fromUtf8("tools_tabs"))
        self.tab_2d = QtGui.QWidget()
        self.tab_2d.setMinimumSize(QtCore.QSize(0, 100))
        self.tab_2d.setObjectName(_fromUtf8("tab_2d"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.tab_2d)
        self.verticalLayout_5.setMargin(0)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.scrollArea_2 = QtGui.QScrollArea(self.tab_2d)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea_2.sizePolicy().hasHeightForWidth())
        self.scrollArea_2.setSizePolicy(sizePolicy)
        self.scrollArea_2.setFrameShape(QtGui.QFrame.NoFrame)
        self.scrollArea_2.setFrameShadow(QtGui.QFrame.Plain)
        self.scrollArea_2.setLineWidth(0)
        self.scrollArea_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName(_fromUtf8("scrollArea_2"))
        self.scrollAreaWidgetContents_2 = QtGui.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 229, 279))
        self.scrollAreaWidgetContents_2.setObjectName(_fromUtf8("scrollAreaWidgetContents_2"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_8.setContentsMargins(0, 10, 0, 0)
        self.verticalLayout_8.setSpacing(10)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.tool2d_explore_radio = QtGui.QRadioButton(self.scrollAreaWidgetContents_2)
        self.tool2d_explore_radio.setChecked(True)
        self.tool2d_explore_radio.setObjectName(_fromUtf8("tool2d_explore_radio"))
        self.verticalLayout_8.addWidget(self.tool2d_explore_radio)
        self.line_8 = QtGui.QFrame(self.scrollAreaWidgetContents_2)
        self.line_8.setFrameShape(QtGui.QFrame.HLine)
        self.line_8.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_8.setObjectName(_fromUtf8("line_8"))
        self.verticalLayout_8.addWidget(self.line_8)
        self.tool2d_draw_points_radio = QtGui.QRadioButton(self.scrollAreaWidgetContents_2)
        self.tool2d_draw_points_radio.setChecked(False)
        self.tool2d_draw_points_radio.setObjectName(_fromUtf8("tool2d_draw_points_radio"))
        self.verticalLayout_8.addWidget(self.tool2d_draw_points_radio)
        self.tool2d_draw_segments_radio = QtGui.QRadioButton(self.scrollAreaWidgetContents_2)
        self.tool2d_draw_segments_radio.setObjectName(_fromUtf8("tool2d_draw_segments_radio"))
        self.verticalLayout_8.addWidget(self.tool2d_draw_segments_radio)
        self.tool2d_draw_polygons_radio = QtGui.QRadioButton(self.scrollAreaWidgetContents_2)
        self.tool2d_draw_polygons_radio.setObjectName(_fromUtf8("tool2d_draw_polygons_radio"))
        self.verticalLayout_8.addWidget(self.tool2d_draw_polygons_radio)
        self.tool2d_draw_polylines_radio = QtGui.QRadioButton(self.scrollAreaWidgetContents_2)
        self.tool2d_draw_polylines_radio.setObjectName(_fromUtf8("tool2d_draw_polylines_radio"))
        self.verticalLayout_8.addWidget(self.tool2d_draw_polylines_radio)
        self.line = QtGui.QFrame(self.scrollAreaWidgetContents_2)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout_8.addWidget(self.line)
        self.tool2d_erase_shapes_radio = QtGui.QRadioButton(self.scrollAreaWidgetContents_2)
        self.tool2d_erase_shapes_radio.setObjectName(_fromUtf8("tool2d_erase_shapes_radio"))
        self.verticalLayout_8.addWidget(self.tool2d_erase_shapes_radio)
        self.line_2 = QtGui.QFrame(self.scrollAreaWidgetContents_2)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.verticalLayout_8.addWidget(self.line_2)
        self.tool2d_select_shapes_radio = QtGui.QRadioButton(self.scrollAreaWidgetContents_2)
        self.tool2d_select_shapes_radio.setObjectName(_fromUtf8("tool2d_select_shapes_radio"))
        self.verticalLayout_8.addWidget(self.tool2d_select_shapes_radio)
        self.tool2d_operation_radio = QtGui.QRadioButton(self.scrollAreaWidgetContents_2)
        self.tool2d_operation_radio.setObjectName(_fromUtf8("tool2d_operation_radio"))
        self.verticalLayout_8.addWidget(self.tool2d_operation_radio)
        self.tool2d_operation_select = QtGui.QComboBox(self.scrollAreaWidgetContents_2)
        self.tool2d_operation_select.setObjectName(_fromUtf8("tool2d_operation_select"))
        self.verticalLayout_8.addWidget(self.tool2d_operation_select)
        self.tool2d_operation_button = QtGui.QPushButton(self.scrollAreaWidgetContents_2)
        self.tool2d_operation_button.setObjectName(_fromUtf8("tool2d_operation_button"))
        self.verticalLayout_8.addWidget(self.tool2d_operation_button)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout_5.addWidget(self.scrollArea_2)
        self.tools_tabs.addTab(self.tab_2d, _fromUtf8(""))
        self.tab_3d = QtGui.QWidget()
        self.tab_3d.setMinimumSize(QtCore.QSize(0, 100))
        self.tab_3d.setObjectName(_fromUtf8("tab_3d"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.tab_3d)
        self.verticalLayout_6.setMargin(0)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.scrollArea = QtGui.QScrollArea(self.tab_3d)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setFrameShape(QtGui.QFrame.NoFrame)
        self.scrollArea.setFrameShadow(QtGui.QFrame.Plain)
        self.scrollArea.setLineWidth(0)
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 229, 218))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_7.setContentsMargins(0, 10, 0, 0)
        self.verticalLayout_7.setSpacing(10)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.tool3d_insert_shape_radio = QtGui.QRadioButton(self.scrollAreaWidgetContents)
        self.tool3d_insert_shape_radio.setChecked(True)
        self.tool3d_insert_shape_radio.setObjectName(_fromUtf8("tool3d_insert_shape_radio"))
        self.verticalLayout_7.addWidget(self.tool3d_insert_shape_radio)
        self.tool3d_insert_shape_select = QtGui.QComboBox(self.scrollAreaWidgetContents)
        self.tool3d_insert_shape_select.setObjectName(_fromUtf8("tool3d_insert_shape_select"))
        self.verticalLayout_7.addWidget(self.tool3d_insert_shape_select)
        self.tool3d_insert_shape_button = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.tool3d_insert_shape_button.setObjectName(_fromUtf8("tool3d_insert_shape_button"))
        self.verticalLayout_7.addWidget(self.tool3d_insert_shape_button)
        self.line_6 = QtGui.QFrame(self.scrollAreaWidgetContents)
        self.line_6.setFrameShape(QtGui.QFrame.HLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName(_fromUtf8("line_6"))
        self.verticalLayout_7.addWidget(self.line_6)
        self.tool3d_erase_shape_radio = QtGui.QRadioButton(self.scrollAreaWidgetContents)
        self.tool3d_erase_shape_radio.setObjectName(_fromUtf8("tool3d_erase_shape_radio"))
        self.verticalLayout_7.addWidget(self.tool3d_erase_shape_radio)
        self.line_7 = QtGui.QFrame(self.scrollAreaWidgetContents)
        self.line_7.setFrameShape(QtGui.QFrame.HLine)
        self.line_7.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_7.setObjectName(_fromUtf8("line_7"))
        self.verticalLayout_7.addWidget(self.line_7)
        self.tool3d_operation_radio = QtGui.QRadioButton(self.scrollAreaWidgetContents)
        self.tool3d_operation_radio.setObjectName(_fromUtf8("tool3d_operation_radio"))
        self.verticalLayout_7.addWidget(self.tool3d_operation_radio)
        self.tool3d_operation_select = QtGui.QComboBox(self.scrollAreaWidgetContents)
        self.tool3d_operation_select.setObjectName(_fromUtf8("tool3d_operation_select"))
        self.verticalLayout_7.addWidget(self.tool3d_operation_select)
        self.tool3d_operation_button = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.tool3d_operation_button.setObjectName(_fromUtf8("tool3d_operation_button"))
        self.verticalLayout_7.addWidget(self.tool3d_operation_button)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_6.addWidget(self.scrollArea)
        self.tools_tabs.addTab(self.tab_3d, _fromUtf8(""))
        self.verticalLayout_2.addWidget(self.tools_tabs)
        self.info_frame = QtGui.QFrame(self.tools_info_frame)
        self.info_frame.setMinimumSize(QtCore.QSize(0, 50))
        self.info_frame.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.info_frame.setFrameShape(QtGui.QFrame.NoFrame)
        self.info_frame.setFrameShadow(QtGui.QFrame.Plain)
        self.info_frame.setObjectName(_fromUtf8("info_frame"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.info_frame)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.tool_info_label = QtGui.QLabel(self.info_frame)
        self.tool_info_label.setMaximumSize(QtCore.QSize(16777215, 13))
        self.tool_info_label.setObjectName(_fromUtf8("tool_info_label"))
        self.verticalLayout_3.addWidget(self.tool_info_label)
        self.info_box = QtGui.QPlainTextEdit(self.info_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.info_box.sizePolicy().hasHeightForWidth())
        self.info_box.setSizePolicy(sizePolicy)
        self.info_box.setMinimumSize(QtCore.QSize(0, 0))
        self.info_box.setMaximumSize(QtCore.QSize(250, 16777215))
        self.info_box.setObjectName(_fromUtf8("info_box"))
        self.verticalLayout_3.addWidget(self.info_box)
        self.horizontalLayout.addWidget(self.tools_info_frame)
        self.console = QtGui.QPlainTextEdit(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.console.sizePolicy().hasHeightForWidth())
        self.console.setSizePolicy(sizePolicy)
        self.console.setMinimumSize(QtCore.QSize(50, 50))
        self.console.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.console.setFrameShape(QtGui.QFrame.NoFrame)
        self.console.setFrameShadow(QtGui.QFrame.Plain)
        self.console.setObjectName(_fromUtf8("console"))
        self.verticalLayout.addWidget(self.splitter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 640, 22))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuView = QtGui.QMenu(self.menubar)
        self.menuView.setObjectName(_fromUtf8("menuView"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.action2D = QtGui.QAction(MainWindow)
        self.action2D.setCheckable(True)
        self.action2D.setObjectName(_fromUtf8("action2D"))
        self.action3D = QtGui.QAction(MainWindow)
        self.action3D.setCheckable(True)
        self.action3D.setObjectName(_fromUtf8("action3D"))
        self.actionReset = QtGui.QAction(MainWindow)
        self.actionReset.setObjectName(_fromUtf8("actionReset"))
        self.menuView.addAction(self.action2D)
        self.menuView.addAction(self.action3D)
        self.menuView.addSeparator()
        self.menuView.addAction(self.actionReset)
        self.menubar.addAction(self.menuView.menuAction())

        self.retranslateUi(MainWindow)
        self.tools_tabs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.label.setText(_translate("MainWindow", "Tools", None))
        self.tool2d_explore_radio.setText(_translate("MainWindow", "Explore Scene", None))
        self.tool2d_draw_points_radio.setText(_translate("MainWindow", "Draw Points", None))
        self.tool2d_draw_segments_radio.setText(_translate("MainWindow", "Draw Segments", None))
        self.tool2d_draw_polygons_radio.setText(_translate("MainWindow", "Draw Polygons", None))
        self.tool2d_draw_polylines_radio.setText(_translate("MainWindow", "Draw Lines", None))
        self.tool2d_erase_shapes_radio.setText(_translate("MainWindow", "Erase Shapes", None))
        self.tool2d_select_shapes_radio.setText(_translate("MainWindow", "Select Shapes", None))
        self.tool2d_operation_radio.setText(_translate("MainWindow", "Operation", None))
        self.tool2d_operation_button.setText(_translate("MainWindow", "Perform Operation", None))
        self.tools_tabs.setTabText(self.tools_tabs.indexOf(self.tab_2d), _translate("MainWindow", "2D", None))
        self.tool3d_insert_shape_radio.setText(_translate("MainWindow", "Insert Shape", None))
        self.tool3d_insert_shape_button.setText(_translate("MainWindow", "Insert Shape", None))
        self.tool3d_erase_shape_radio.setText(_translate("MainWindow", "Erase Shape", None))
        self.tool3d_operation_radio.setText(_translate("MainWindow", "Operation", None))
        self.tool3d_operation_button.setText(_translate("MainWindow", "Perform Operation", None))
        self.tools_tabs.setTabText(self.tools_tabs.indexOf(self.tab_3d), _translate("MainWindow", "3D", None))
        self.tool_info_label.setText(_translate("MainWindow", "Tool Info", None))
        self.menuView.setTitle(_translate("MainWindow", "View", None))
        self.action2D.setText(_translate("MainWindow", "2D", None))
        self.action2D.setToolTip(_translate("MainWindow", "Switch to 2D View", None))
        self.action2D.setShortcut(_translate("MainWindow", "Ctrl+2", None))
        self.action3D.setText(_translate("MainWindow", "3D", None))
        self.action3D.setToolTip(_translate("MainWindow", "Switch to 2D View", None))
        self.action3D.setShortcut(_translate("MainWindow", "Ctrl+3", None))
        self.actionReset.setText(_translate("MainWindow", "Reset", None))
        self.actionReset.setShortcut(_translate("MainWindow", "Ctrl+R", None))

from app.canvas3d import Canvas3d

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

